#!/bin/bash
rm -rf indienen/
rm indienen.zip
mkdir indienen
folder=indienen/
cp -r project/src/heap indienen/
cp -r project/test indienen/
cp -r verslag/verslag.pdf indienen/
rm indienen/heap/Heap.java
rm indienen/heap/EmptyHeapException.java
rm indienen/heap/Heaps.java
rm indienen/heap/Element.java
cd indienen; zip -r ../indienen.zip *
